---
branches:
  except:
    - gh-pages
  only:
    - master
skip_tags: true

build_script:
  -
    ps: "mvn -B clean install -DskipTests=true"
cache:
  - "C:\\maven\\"
  - "C:\\Users\\appveyor\\.m2"
# set clone depth
clone_depth: 5
environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  MAVEN_OPTS: "-Xms2048m -Xmx2048m"
init:
  - git config --global core.autocrlf input
install:
  -
    ps: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        if(!(Test-Path -Path \"C:\\maven\\apache-maven-3.3.9\"))
        {
           echo 'Downloading Maven '
           (new-object System.Net.WebClient).DownloadFile('http://redrockdigimark.com/apachemirror/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip',
           'C:\\apache-maven-3.3.9-bin.zip')
           [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\\apache-maven-3.3.9-bin.zip','C:\\maven')
        }
        Set PATH="C:\\maven\\apache-maven-3.3.9\\bin;%PATH%"
test_script:
  -
    ps: "mvn -B clean install"
version: 1.0-SNAPSHOT.{build}

