= fabric8 Maven Plugin OpenShift Build Config Enricher

This fabric8 maven plugin enricher API allows the `fabric8:deploy` goal to create a build config using

https://docs.openshift.org/latest/install_config/configuring_pipeline_execution.html[Configuring Pipeline Execution]

[WARNING]
====
 * Currently supports only Jenkins Pipeline Build Strategy
 * This enricher is still under development, and expect changes
====

== Build

This plugin is not available in maven central, so you have to build and install locally before proceeding further.

Clone the repo https://github.com/kameshsampath/fmp-openshift-bc-enricher and run `./mvnw clean install` from $PROJECT_HOME

== Usage

Create https://maven.fabric8.io/#profiles[fabric8 maven plugin profile] called *profiles.yml* inside `$basedir/src/main/fabric8`.

The following example shows a profile which can be used in conjunction with spring-boot app. Please refer to https://maven.fabric8.io/#profiles[fabric8 maven plugin profile] for more details

[source,yaml]
----
- name: jenkins-springboot-app
  enricher:
    # The order given in "includes" is the order in which enrichers are called
    includes:
    - fmp-name
    - fmp-controller
    - fmp-service
    - fmp-image
    - fmp-portname
    - fmp-project
    - fmp-pod-annotations
    - fmp-debug
    - fmp-merge
    - fmp-remove-build-annotations
    - fmp-volume-permission
    - fmp-openshift-bc-enricher
    - f8-expose
    # Health checks
    - spring-boot-health-check
    - docker-health-check
    - fmp-dependency
    - f8-watch
  generator:
    # The order given in "includes" is the order in which generators are called
    includes:
    - spring-boot
  watcher:
    includes:
    - spring-boot
    - docker-image

----

Add the following fabric8-maven-plugin configuration to the project,

[source,xml]
----
 <plugin>
     <groupId>io.fabric8</groupId>
     <artifactId>fabric8-maven-plugin</artifactId>
     <version>3.5.30</version>

     <dependencies>
       <dependency>
         <groupId>org.workspace7.fmp</groupId>
         <artifactId>fmp-openshift-bc-enricher</artifactId> <1>
         <version>0.1-SNAPSHOT</version>
       </dependency>
     </dependencies>

     <configuration>
       <profile>jenkins-springboot-app</profile> <2>
       <enricher>
         <config>
         <fmp-openshift-bc-enricher>
           <genericSecret>abcde</genericSecret> <3>
           <githubWebHookSecret>wxyz</githubWebHookSecret> <4>
         </fmp-openshift-bc-enricher>
         </config>
       </enricher>
     </configuration>

     <executions>
       <execution>
         <goals>
           <goal>build</goal>
           <goal>resource</goal>
         </goals>
       </execution>
     </executions>
</plugin>
----
<1> add the fmp-openshift-bc-enricher as dependnecy to the fabric8-maven-plugin
<2> should be name that was used in the `profiles.yaml` above
<3> The Generic secret that will be used to trigger the build
<4> The GitHub Webhook Secret that will be used to trigger the build

== Add Jenkinsfile

Add the following jenkins file to the project

```
node("fmp-maven") {
  checkout scm
  stage("Test") {
    sh "mvn test"
  }
  stage("Deploy") {
    sh "mvn fabric8:deploy -DskipTests"
  }
}
```

[NOTE]
====

This is a sample Jenkins file, for more samples refer to resources <<jenkinsfile-samples>>

====

== Resources

* https://blog.openshift.com/openshift-pipelines-jenkins-blue-ocean/

[[jenkinsfile-samples]]
=== Samples

* https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline
* https://github.com/fabric8io/fabric8-jenkinsfile-library

=== Reusable Jenkins Pipleline steps

* https://github.com/fabric8io/fabric8-pipeline-library